import type {
  IamInvitation,
  IamLogEvent,
  IamPermissionGroup,
  IamRole,
  IamSession,
  IamTeam,
  IamUser,
} from "../types"

export const IAM_WORKSPACES = ["Madar Growth", "Retail Expansion", "Enterprise Pipeline"]

export const IAM_PERMISSION_GROUPS: IamPermissionGroup[] = [
  { module: "dashboard", label: "Dashboard", actions: ["view", "export"] },
  {
    module: "campaigns",
    label: "Campaigns",
    actions: ["view", "create", "edit", "delete", "approve", "publish"],
  },
  {
    module: "customers",
    label: "Customers",
    actions: ["view", "create", "edit", "delete", "export", "import"],
  },
  {
    module: "products",
    label: "Products",
    actions: ["view", "create", "edit", "delete", "export", "import"],
  },
  { module: "reports", label: "Reports", actions: ["view", "export", "approve"] },
  {
    module: "connections",
    label: "Connections",
    actions: ["view", "create", "edit", "delete", "manage"],
  },
  {
    module: "creativeLibrary",
    label: "Creative Library",
    actions: ["view", "create", "edit", "delete", "publish"],
  },
  { module: "ai", label: "AI", actions: ["view", "manage"] },
  { module: "settings", label: "Settings", actions: ["view", "edit", "manage"] },
  { module: "workspace", label: "Workspace", actions: ["view", "edit", "manage"] },
  { module: "users", label: "Users", actions: ["view", "create", "edit", "delete", "manage"] },
  { module: "billing", label: "Billing", actions: ["view", "edit", "manage"] },
  { module: "notifications", label: "Notifications", actions: ["view", "edit", "manage"] },
  { module: "api", label: "API", actions: ["view", "create", "delete", "manage"] },
]

function buildPermissions(overrides: Partial<IamRole["permissions"]> = {}): IamRole["permissions"] {
  const baseline = Object.fromEntries(
    IAM_PERMISSION_GROUPS.map((group) => [group.module, ["view"]])
  ) as IamRole["permissions"]
  return {
    ...baseline,
    ...overrides,
  }
}

export const IAM_ROLES: IamRole[] = [
  {
    id: "owner",
    name: "Owner",
    description: "Full control across security, billing, and workspace governance.",
    userCount: 1,
    isDefault: true,
    permissions: Object.fromEntries(
      IAM_PERMISSION_GROUPS.map((group) => [group.module, group.actions])
    ) as IamRole["permissions"],
  },
  {
    id: "administrator",
    name: "Administrator",
    description: "Manages users, roles, and operational settings.",
    userCount: 3,
    isDefault: true,
    permissions: buildPermissions({
      campaigns: ["view", "create", "edit", "delete", "approve", "publish"],
      users: ["view", "create", "edit", "delete", "manage"],
      workspace: ["view", "edit", "manage"],
      settings: ["view", "edit", "manage"],
    }),
  },
  {
    id: "marketing-manager",
    name: "Marketing Manager",
    description: "Owns campaign planning, approvals, and reporting.",
    userCount: 8,
    isDefault: true,
    permissions: buildPermissions({
      campaigns: ["view", "create", "edit", "approve", "publish"],
      reports: ["view", "export"],
      creativeLibrary: ["view", "create", "edit", "publish"],
    }),
  },
  {
    id: "marketing-specialist",
    name: "Marketing Specialist",
    description: "Executes daily campaign operations and creative updates.",
    userCount: 11,
    isDefault: true,
    permissions: buildPermissions({
      campaigns: ["view", "create", "edit"],
      creativeLibrary: ["view", "create", "edit"],
      reports: ["view"],
    }),
  },
  {
    id: "performance-analyst",
    name: "Performance Analyst",
    description: "Analyzes KPI trends and exports reporting data.",
    userCount: 6,
    isDefault: true,
    permissions: buildPermissions({
      dashboard: ["view", "export"],
      reports: ["view", "export"],
      campaigns: ["view"],
    }),
  },
  {
    id: "designer",
    name: "Designer",
    description: "Produces and manages campaign creatives.",
    userCount: 4,
    isDefault: true,
    permissions: buildPermissions({
      creativeLibrary: ["view", "create", "edit", "publish"],
      campaigns: ["view"],
    }),
  },
  {
    id: "finance",
    name: "Finance",
    description: "Reviews budget movements and billing records.",
    userCount: 2,
    isDefault: true,
    permissions: buildPermissions({
      billing: ["view", "edit"],
      reports: ["view", "export"],
      campaigns: ["view"],
    }),
  },
  {
    id: "viewer",
    name: "Viewer",
    description: "Read-only access across approved modules.",
    userCount: 13,
    isDefault: true,
    permissions: buildPermissions(),
  },
  {
    id: "custom-revops",
    name: "Custom Role",
    description: "Custom role prepared for RevOps workflows.",
    userCount: 2,
    isDefault: false,
    permissions: buildPermissions({
      campaigns: ["view", "edit"],
      customers: ["view", "edit", "export"],
      reports: ["view", "export"],
      users: ["view"],
    }),
  },
]

export const IAM_USERS: IamUser[] = [
  {
    id: "u1",
    fullName: "Ahmed Al-Qahtani",
    email: "ahmed@madar.ai",
    department: "Marketing",
    roleId: "marketing-manager",
    workspaces: ["Madar Growth", "Retail Expansion"],
    status: "active",
    lastLogin: "2 minutes ago",
    mfaEnabled: true,
    teams: ["Marketing", "Leadership"],
    recentActivity: ["Approved campaign budget", "Published Ramadan creative"],
    devices: [
      { name: "MacBook Pro", browser: "Chrome", lastActive: "Now" },
      { name: "iPhone 15", browser: "Safari", lastActive: "1h ago" },
    ],
  },
  {
    id: "u2",
    fullName: "Sara Al-Mutairi",
    email: "sara@madar.ai",
    department: "Design",
    roleId: "designer",
    workspaces: ["Madar Growth"],
    status: "active",
    lastLogin: "18 minutes ago",
    mfaEnabled: true,
    teams: ["Design", "Content"],
    recentActivity: ["Uploaded 6 creative assets", "Updated hero visual set"],
    devices: [{ name: "Dell XPS", browser: "Edge", lastActive: "18m ago" }],
  },
  {
    id: "u3",
    fullName: "Ali Basim",
    email: "ali@madar.ai",
    department: "Performance",
    roleId: "performance-analyst",
    workspaces: ["Enterprise Pipeline"],
    status: "active",
    lastLogin: "4 hours ago",
    mfaEnabled: false,
    teams: ["Performance"],
    recentActivity: ["Exported weekly KPI report", "Created ROAS dashboard view"],
    devices: [{ name: "ThinkPad", browser: "Firefox", lastActive: "4h ago" }],
  },
  {
    id: "u4",
    fullName: "Nora Al-Harbi",
    email: "nora@madar.ai",
    department: "Leadership",
    roleId: "owner",
    workspaces: ["Madar Growth", "Retail Expansion", "Enterprise Pipeline"],
    status: "active",
    lastLogin: "Yesterday",
    mfaEnabled: true,
    teams: ["Leadership"],
    recentActivity: ["Changed role permissions", "Accepted pending invitation"],
    devices: [
      { name: "MacBook Air", browser: "Chrome", lastActive: "Yesterday" },
      { name: "iPad Pro", browser: "Safari", lastActive: "2d ago" },
    ],
  },
  {
    id: "u5",
    fullName: "Rashed Fahad",
    email: "rashed@madar.ai",
    department: "Finance",
    roleId: "finance",
    workspaces: ["Retail Expansion"],
    status: "inactive",
    lastLogin: "12 days ago",
    mfaEnabled: false,
    teams: ["Leadership"],
    recentActivity: ["Reviewed monthly billing report"],
    devices: [{ name: "Windows Desktop", browser: "Edge", lastActive: "12d ago" }],
  },
]

export const IAM_TEAMS: IamTeam[] = [
  {
    id: "t1",
    name: "Marketing",
    manager: "Ahmed Al-Qahtani",
    members: 12,
    workspace: "Madar Growth",
    description: "Campaign planning and lifecycle execution.",
    color: "bg-blue-500",
  },
  {
    id: "t2",
    name: "Performance",
    manager: "Ali Basim",
    members: 7,
    workspace: "Enterprise Pipeline",
    description: "Optimization, attribution, and insights.",
    color: "bg-emerald-500",
  },
  {
    id: "t3",
    name: "Content",
    manager: "Sara Al-Mutairi",
    members: 6,
    workspace: "Madar Growth",
    description: "Messaging and social content operations.",
    color: "bg-amber-500",
  },
  {
    id: "t4",
    name: "Design",
    manager: "Sara Al-Mutairi",
    members: 5,
    workspace: "Retail Expansion",
    description: "Creative production and brand consistency.",
    color: "bg-fuchsia-500",
  },
  {
    id: "t5",
    name: "CRM",
    manager: "Maha Salem",
    members: 4,
    workspace: "Retail Expansion",
    description: "Lead nurturing and lifecycle engagement.",
    color: "bg-cyan-500",
  },
  {
    id: "t6",
    name: "Leadership",
    manager: "Nora Al-Harbi",
    members: 3,
    workspace: "Enterprise Pipeline",
    description: "Executive governance and approvals.",
    color: "bg-slate-500",
  },
]

export const IAM_INVITATIONS: IamInvitation[] = [
  {
    id: "i1",
    email: "fatima@agency.sa",
    roleId: "marketing-specialist",
    workspace: "Madar Growth",
    department: "Marketing",
    status: "pending",
    invitedAt: "2026-06-11",
    expiresAt: "2026-06-25",
  },
  {
    id: "i2",
    email: "omar@partner.co",
    roleId: "viewer",
    workspace: "Retail Expansion",
    department: "Partnerships",
    status: "accepted",
    invitedAt: "2026-06-01",
    expiresAt: "2026-06-15",
  },
  {
    id: "i3",
    email: "noor@consulting.io",
    roleId: "performance-analyst",
    workspace: "Enterprise Pipeline",
    department: "Performance",
    status: "expired",
    invitedAt: "2026-05-10",
    expiresAt: "2026-05-24",
  },
]

export const IAM_ACTIVITY_LOGS: IamLogEvent[] = [
  {
    id: "a1",
    actor: "Ahmed Al-Qahtani",
    action: "created campaign",
    target: "Summer Promo KSA",
    category: "activity",
    createdAt: "2026-06-19 09:32",
  },
  {
    id: "a2",
    actor: "Sara Al-Mutairi",
    action: "uploaded creative",
    target: "Carousel Variant B",
    category: "activity",
    createdAt: "2026-06-19 08:58",
  },
  {
    id: "a3",
    actor: "Ali Basim",
    action: "connected integration",
    target: "Google Ads Workspace",
    category: "activity",
    createdAt: "2026-06-18 17:40",
  },
  {
    id: "a4",
    actor: "Nora Al-Harbi",
    action: "changed campaign budget",
    target: "Enterprise Retargeting",
    category: "activity",
    createdAt: "2026-06-18 11:22",
  },
]

export const IAM_AUDIT_LOGS: IamLogEvent[] = [
  {
    id: "l1",
    actor: "Nora Al-Harbi",
    action: "role changed",
    target: "Marketing Specialist -> Added approve permission",
    category: "audit",
    createdAt: "2026-06-19 10:03",
    severity: "high",
  },
  {
    id: "l2",
    actor: "Ahmed Al-Qahtani",
    action: "invitation accepted",
    target: "fatima@agency.sa",
    category: "audit",
    createdAt: "2026-06-19 09:12",
    severity: "medium",
  },
  {
    id: "l3",
    actor: "System",
    action: "failed login",
    target: "ali@madar.ai",
    category: "audit",
    createdAt: "2026-06-19 08:47",
    severity: "high",
  },
  {
    id: "l4",
    actor: "Sara Al-Mutairi",
    action: "mfa enabled",
    target: "sara@madar.ai",
    category: "audit",
    createdAt: "2026-06-18 21:15",
    severity: "low",
  },
]

export const IAM_SESSIONS: IamSession[] = [
  {
    id: "s1",
    browser: "Chrome 126",
    device: "MacBook Pro 14",
    ip: "41.90.12.20",
    location: "Riyadh, SA",
    loginTime: "2026-06-19 08:21",
    lastActivity: "Now",
    current: true,
  },
  {
    id: "s2",
    browser: "Safari 18",
    device: "iPhone 15",
    ip: "41.90.12.20",
    location: "Riyadh, SA",
    loginTime: "2026-06-18 20:11",
    lastActivity: "2h ago",
    current: false,
  },
  {
    id: "s3",
    browser: "Edge 126",
    device: "Windows Desktop",
    ip: "95.174.77.10",
    location: "Jeddah, SA",
    loginTime: "2026-06-17 09:02",
    lastActivity: "1d ago",
    current: false,
  },
]
