import type {
  DashboardPackageDto,
  DashboardWidgetReadModelPayload,
} from "@/application/contracts/dashboard.contracts"

export const marketingDashboardPackageDto: DashboardPackageDto = {
  id: "marketing-dashboard",
  persona: "marketing-operator",
  widgets: [
    "welcome-banner",
    "revenue-chart",
    "visitors-chart",
    "activity-insights",
    "website-analytics",
    "transactions-card",
    "completion-rate",
    "browser-stats",
    "traffic-table",
    "social-stats",
  ],
  layout: [
    { widgetId: "welcome-banner", zone: "hero", order: 0, responsive: { mobile: 12, desktop: 6 } },
    {
      widgetId: "revenue-chart",
      zone: "executive",
      order: 0,
      responsive: { mobile: 12, tablet: 6, desktop: 3 },
    },
    {
      widgetId: "visitors-chart",
      zone: "executive",
      order: 1,
      responsive: { mobile: 12, tablet: 6, desktop: 3 },
    },
    {
      widgetId: "activity-insights",
      zone: "analytics",
      order: 0,
      responsive: { mobile: 12, desktop: 6 },
    },
    {
      widgetId: "website-analytics",
      zone: "analytics",
      order: 1,
      responsive: { mobile: 12, desktop: 6 },
    },
    {
      widgetId: "transactions-card",
      zone: "diagnostics",
      order: 0,
      responsive: {
        mobile: 12,
        tablet: 6,
        tabletBreakpoint: "lg",
        desktop: 4,
        utilityClassName: "flex",
      },
    },
    {
      widgetId: "completion-rate",
      zone: "diagnostics",
      order: 1,
      responsive: {
        mobile: 12,
        tablet: 6,
        tabletBreakpoint: "lg",
        desktop: 4,
        utilityClassName: "flex",
      },
    },
    {
      widgetId: "browser-stats",
      zone: "diagnostics",
      order: 2,
      responsive: { mobile: 12, desktop: 4, utilityClassName: "flex" },
    },
    {
      widgetId: "traffic-table",
      zone: "operations",
      order: 0,
      responsive: { mobile: 12, desktop: 8, utilityClassName: "flex" },
    },
    {
      widgetId: "social-stats",
      zone: "footer",
      order: 0,
      responsive: { mobile: 12, desktop: 4, utilityClassName: "flex" },
    },
  ],
  permissions: ["dashboard:view"],
  featureFlags: [],
  themePreset: "dark-blue",
  defaultFilters: {},
  version: "1.0.0",
}

export const dashboardWidgetPayloadDtos: Record<string, DashboardWidgetReadModelPayload> = {
  "welcome-banner": {
    widgetId: "welcome-banner",
    title: "لوحة التسويق التنفيذية",
    summary: "أداء قوي هذا الربع: نمو الإيراد +18% وتحسن ROAS إلى 3.4 مع انخفاض CAC بنسبة 9%.",
    dataPoints: [
      {
        revenue: 1248000,
        marketingSpend: 364000,
        roas: 3.43,
        cac: 41,
        conversionRate: 4.8,
        activeCampaigns: 12,
      },
    ],
  },
  "revenue-chart": {
    widgetId: "revenue-chart",
    title: "إجمالي الإيرادات",
    summary: "اتجاه الإيرادات الشهرية مقابل الإنفاق التسويقي.",
    dataPoints: [
      { month: "Jan", value: 148000, spend: 51000 },
      { month: "Feb", value: 164000, spend: 54000 },
      { month: "Mar", value: 172000, spend: 56000 },
      { month: "Apr", value: 201000, spend: 61000 },
      { month: "May", value: 226000, spend: 67000 },
      { month: "Jun", value: 235000, spend: 75000 },
    ],
  },
  "visitors-chart": {
    widgetId: "visitors-chart",
    title: "زوار الموقع",
    summary: "تطور الزوار والجلسات ومعدل الارتداد.",
    dataPoints: [
      { month: "Jan", visitors: 42200, sessions: 65800, bounceRate: 43.2 },
      { month: "Feb", visitors: 46800, sessions: 70200, bounceRate: 41.7 },
      { month: "Mar", visitors: 49300, sessions: 73100, bounceRate: 40.9 },
      { month: "Apr", visitors: 53700, sessions: 79200, bounceRate: 39.8 },
      { month: "May", visitors: 57400, sessions: 84600, bounceRate: 38.4 },
      { month: "Jun", visitors: 61200, sessions: 90300, bounceRate: 37.6 },
    ],
  },
  "activity-insights": {
    widgetId: "activity-insights",
    title: "رؤى الأداء التسويقي",
    summary: "مؤشرات الحملة: مشاهدات، نقرات، تحويلات، وتنبيهات الأداء.",
    dataPoints: [
      { month: "Jan", impressions: 1180000, clicks: 43800, leads: 2180, alerts: 3 },
      { month: "Feb", impressions: 1240000, clicks: 46200, leads: 2410, alerts: 2 },
      { month: "Mar", impressions: 1300000, clicks: 48900, leads: 2580, alerts: 2 },
      { month: "Apr", impressions: 1370000, clicks: 52100, leads: 2760, alerts: 1 },
      { month: "May", impressions: 1430000, clicks: 54900, leads: 2910, alerts: 1 },
      { month: "Jun", impressions: 1490000, clicks: 57400, leads: 3090, alerts: 1 },
    ],
  },
  "website-analytics": {
    widgetId: "website-analytics",
    title: "تحليلات الموقع",
    summary: "مقاييس العملاء الجدد، التحويل، والقيمة المتوقعة لكل عميل.",
    dataPoints: [
      {
        totalUsers: 685700,
        revenue: 7926,
        revenueDelta: 12,
        activeUsers: 428,
        activeDelta: 8,
        conversionRate: 3.6,
        conversionDelta: -2,
      },
    ],
  },
  "transactions-card": {
    widgetId: "transactions-card",
    title: "أداء الحملات النشطة",
    summary: "أحدث نتائج الحملات عبر القنوات الرئيسية.",
    dataPoints: [
      { name: "Meta Retargeting", date: "Jun 15", status: "مربحة", amount: 14300 },
      { name: "Google Search KSA", date: "Jun 14", status: "مستقرة", amount: 9800 },
      { name: "TikTok Prospecting", date: "Jun 13", status: "منخفضة", amount: 6200 },
      { name: "Snapchat Ramadan", date: "Jun 12", status: "مربحة", amount: 11800 },
      { name: "YouTube Awareness", date: "Jun 11", status: "مستقرة", amount: 7400 },
      { name: "Email Reactivation", date: "Jun 10", status: "مربحة", amount: 8700 },
    ],
  },
  "completion-rate": {
    widgetId: "completion-rate",
    title: "معدل التحويل",
    summary: "تطور معدل التحويل وعرض ملخص قمع التسويق.",
    dataPoints: [
      { month: "Jan", completion: 3.8 },
      { month: "Feb", completion: 4.1 },
      { month: "Mar", completion: 4.3 },
      { month: "Apr", completion: 4.6 },
      { month: "May", completion: 4.7 },
      { month: "Jun", completion: 4.8 },
    ],
  },
  "browser-stats": {
    widgetId: "browser-stats",
    title: "أعلى القنوات",
    summary: "توزيع الزوار حسب القناة التسويقية.",
    dataPoints: [
      { channel: "Meta", visitors: 27500 },
      { channel: "Google", visitors: 31200 },
      { channel: "TikTok", visitors: 18700 },
      { channel: "Snapchat", visitors: 14300 },
      { channel: "Email", visitors: 9600 },
    ],
  },
  "traffic-table": {
    widgetId: "traffic-table",
    title: "مصادر الزيارات",
    summary: "جلسات، معدل الارتداد، والتحسن الشهري حسب المصدر.",
    dataPoints: [
      {
        month: "Jan",
        source: "Google",
        desktop: 186,
        mobile: 80,
        sessions: 4200,
        bounce: 42,
        growth: -4.2,
      },
      {
        month: "Feb",
        source: "Meta",
        desktop: 305,
        mobile: 200,
        sessions: 6850,
        bounce: 38,
        growth: 7.1,
      },
      {
        month: "Mar",
        source: "TikTok",
        desktop: 237,
        mobile: 120,
        sessions: 5120,
        bounce: 46,
        growth: -2.4,
      },
      {
        month: "Apr",
        source: "Direct",
        desktop: 273,
        mobile: 190,
        sessions: 5980,
        bounce: 40,
        growth: 3.9,
      },
      {
        month: "May",
        source: "Snapchat",
        desktop: 309,
        mobile: 230,
        sessions: 7340,
        bounce: 35,
        growth: 5.6,
      },
      {
        month: "Jun",
        source: "LinkedIn",
        desktop: 334,
        mobile: 240,
        sessions: 7680,
        bounce: 33,
        growth: 6.1,
      },
    ],
  },
  "social-stats": {
    widgetId: "social-stats",
    title: "الأداء الاجتماعي",
    summary: "أداء القنوات الاجتماعية من حيث الوصول والتحويل.",
    dataPoints: [
      { channel: "Facebook", category: "Awareness", value: 45689, change: 28.5 },
      { channel: "Instagram", category: "Engagement", value: 39420, change: 12.9 },
      { channel: "TikTok", category: "Video", value: 51234, change: 34.1 },
      { channel: "X", category: "Community", value: 18214, change: -9.5 },
      { channel: "Snapchat", category: "Acquisition", value: 33108, change: 21.4 },
    ],
  },
}

export function waitForDashboardMock(duration = 30) {
  return new Promise((resolve) => {
    setTimeout(resolve, duration)
  })
}
