-- ZATCA (Saudi e-invoicing) Phase 1 -- Generation Phase -- fields for pos_invoices, plus a
-- per-workspace invoice-number counter that replaces pos_invoice_number_seq.
--
-- pos_invoice_number_seq (055_pos_invoices.sql) is ONE sequence shared by every organization on
-- this platform: the moment two tenants both ring up a sale, either tenant's own invoice log
-- shows a gap where the other tenant's number landed. ZATCA explicitly prohibits gaps in an
-- establishment's own invoice sequence. It is also fetched via a plain `SELECT nextval(...)`
-- BEFORE invoices-service.ts's create() opens its transaction, so a rolled-back create() still
-- permanently burns a number -- a real, unrecoverable gap. pos_invoice_number_counters fixes
-- both: one counter row per workspace (branch), incremented with an UPSERT that invoices-
-- service.ts now runs INSIDE the same transaction as the invoice insert, so a rollback reverts
-- the counter too. pos_invoice_number_seq is dropped since nothing references it after that
-- change lands in the same commit.
create table if not exists pos_invoice_number_counters (
  workspace_id uuid primary key references workspaces(id),
  next_number bigint not null default 1
);

-- Seed each workspace's counter from the highest number it already has under the old global
-- sequence -- without this, a workspace that already owns invoices 1..21 would have its very
-- first post-migration sale try to reissue "INV-000001", colliding with its own historical row.
-- invoices-service.ts's UPSERT always reads a counter row's current value as "the number most
-- recently issued" (it increments-then-returns), so seeding it to the real historical max, not
-- max+1, is correct -- the next real call naturally continues one past it. Safe to replay on
-- every boot (no migration-tracking table in this codebase): once seeded, the computed max can
-- only ever equal the counter's already-correct value, so the GREATEST below is a no-op from
-- then on.
-- LIKE rather than a regex anchor: pg-mem (this codebase's test harness) has no `~` operator, and
-- every invoice_number here was always generated by this same app as literally "INV-" + digits,
-- so there is no untrusted format to guard against more strictly.
insert into pos_invoice_number_counters (workspace_id, next_number)
select workspace_id, max(cast(substring(invoice_number, 5, 6) as bigint))
  from pos_invoices
 where invoice_number like 'INV-%'
 group by workspace_id
on conflict (workspace_id) do update
  set next_number = greatest(pos_invoice_number_counters.next_number, excluded.next_number);

drop sequence if exists pos_invoice_number_seq;

-- invoice_number was globally unique (055_pos_invoices.sql) because the single global sequence
-- it came from made global uniqueness trivial. Now that numbering is per-workspace, two
-- different branches legitimately produce the SAME number (their own independent "INV-000001"),
-- exactly like two separate stores both having a receipt #1 -- so the constraint has to scope to
-- (workspace_id, invoice_number) instead, or the very first time two workspaces' counters
-- overlap, invoice creation starts failing with a duplicate-key error.
alter table pos_invoices drop constraint if exists pos_invoices_invoice_number_key;
alter table pos_invoices drop constraint if exists pos_invoices_workspace_invoice_number_key;
alter table pos_invoices
  add constraint pos_invoices_workspace_invoice_number_key unique (workspace_id, invoice_number);

-- Same issue, one level removed: a deferred/wallet-funded sale's customer_account_transactions
-- row reuses the invoice number as its `reference` (invoices-service.ts's create()), and that
-- column was also globally unique (066_customer_unified_account.sql). Scoped the same way and
-- for the same reason -- a receipt/payment voucher's reference keeps its own separate sequence
-- (RCT-/PAY-) and was never at risk, but a sale's was.
alter table customer_account_transactions drop constraint if exists customer_account_transactions_reference_key;
alter table customer_account_transactions drop constraint if exists customer_account_transactions_workspace_reference_key;
alter table customer_account_transactions
  add constraint customer_account_transactions_workspace_reference_key unique (workspace_id, reference);

-- ZATCA TLV QR payload (Base64), generated deterministically from the invoice's own seller/total/
-- VAT fields at issuance time -- see zatca-qr-code.ts. Generated on every sale regardless of
-- whether the organization has a VAT number on file yet (see invoices-service.ts's
-- loadSellerSnapshot): an unset VAT number just leaves that one TLV tag empty rather than
-- fabricated, it never blocks the QR (or the sale) outright. Only null for an invoice issued
-- before this column existed.
alter table pos_invoices add column if not exists qr_code text;

-- Seller identity/address as it stood in organizations.settings at the moment this invoice was
-- issued -- a snapshot, not a live join, so a later edit to the organization's tax profile can
-- never rewrite what an already-issued invoice says about itself. Nullable for the same reason
-- qr_code is: not every organization has completed its tax profile yet.
alter table pos_invoices add column if not exists seller_name text;
alter table pos_invoices add column if not exists seller_vat_number text;
alter table pos_invoices add column if not exists seller_address text;

-- Phase 2 (Integration Phase) columns -- deliberately left unused by any application code in this
-- migration. They exist now purely so Phase 2 (FATOORA API reporting/clearance, cryptographic
-- stamping, hash-chaining) can be added later without another structural migration to this table.
alter table pos_invoices add column if not exists icv bigint;
alter table pos_invoices add column if not exists previous_invoice_hash text;
alter table pos_invoices add column if not exists invoice_hash text;
alter table pos_invoices add column if not exists cryptographic_stamp text;
alter table pos_invoices add column if not exists zatca_status text;
alter table pos_invoices add column if not exists zatca_response jsonb;
