export const ROUTES = {
  home: "/",
  dashboard: "/dashboard/analytics",
  workspaceSelect: "/workspace/select",
  channels: "/channels",
  campaigns: "/campaigns",
  campaignsCreate: "/campaigns/new",
  campaignsDetails: (campaignId: string) => `/campaigns/${campaignId}`,
  campaignsEdit: (campaignId: string) => `/campaigns/${campaignId}/edit`,
  stores: "/stores",
  products: "/products",
  productsAdd: "/eCommerce/add-product",
  customers: "/customers",
  customersDetails: (customerId: string) => `/customers/${customerId}`,
  reports: "/reports",
  ai: "/ai",
  integrations: "/integrations",
  integrationsNew: "/integrations/new",
  integrationsHealth: "/integrations/health",
  integrationsDetails: (connectionId: string) => `/integrations/${connectionId}`,
  integrationsSettings: (connectionId: string) => `/integrations/${connectionId}/settings`,
  integrationsHistory: (connectionId: string) => `/integrations/${connectionId}/history`,
  administration: "/administration",
  administrationUsers: "/administration/users",
  administrationRoles: "/administration/roles",
  administrationPermissions: "/administration/permissions",
  administrationTeams: "/administration/teams",
  administrationInvitations: "/administration/invitations",
  administrationActivityLog: "/administration/activity-log",
  administrationAuditLog: "/administration/audit-log",
  administrationSessions: "/administration/sessions",
  settings: "/settings",
  auth: {
    basic: {
      login: "/auth/basic/login",
      register: "/auth/basic/register",
      forgotPassword: "/auth/basic/forgot-password",
      resetPassword: "/auth/basic/reset-password",
      verifyEmail: "/auth/basic/verify-email",
      passwordResetSuccess: "/auth/basic/password-reset-success",
    },
    cover: {
      login: "/auth/cover/login",
      register: "/auth/cover/register",
      forgotPassword: "/auth/cover/forgot-password",
      resetPassword: "/auth/cover/reset-password",
      verifyEmail: "/auth/cover/verify-email",
      passwordResetSuccess: "/auth/cover/password-reset-success",
    },
  },
  login: "/auth/basic/login",
  register: "/auth/basic/register",
  privacy: "/privacy",
  forgotPassword: "/auth/basic/forgot-password",
  resetPassword: "/auth/basic/reset-password",
  verifyEmail: "/auth/basic/verify-email",
  passwordResetSuccess: "/auth/basic/password-reset-success",
} as const
