export const ROUTES = {
  home: "/",
  dashboard: "/dashboard/analytics",
  workspaceSelect: "/workspace/select",
  channels: "/channels",
  campaigns: "/campaigns",
  campaignsCreate: "/campaigns/new",
  campaignsDetails: (campaignId: string) => `/campaigns/${campaignId}`,
  campaignsEdit: (campaignId: string) => `/campaigns/${campaignId}/edit`,
  campaignLinks: "/campaigns/links",
  liveVisitors: "/live-visitors",
  marketplace: "/marketplace",
  marketplaceDetails: (appId: string) => `/marketplace/${appId}`,
  stores: "/stores",
  products: "/products",
  productsAdd: "/eCommerce/add-product",
  orders: "/orders",
  pos: "/pos",
  shifts: "/shifts",
  shiftsDetails: (shiftId: string) => `/shifts/${shiftId}`,
  invoices: "/invoices",
  invoicesReturns: "/invoices/returns",
  customers: "/customers",
  customerStatement: (customerId: string) => `/customers/${customerId}/statement`,
  reports: "/reports",
  reportsKpis: "/reports/kpis",
  reportsKpisNew: "/reports/kpis/new",
  reportsKpisEdit: (kpiId: string) => `/reports/kpis/${kpiId}/edit`,
  reportsCustomNew: "/reports/custom/new",
  reportsCustomEdit: (reportId: string) => `/reports/custom/${reportId}/edit`,
  reportsCustomView: (reportId: string) => `/reports/custom/${reportId}`,
  ai: "/ai",
  integrations: "/integrations",
  integrationsNew: "/integrations/new",
  integrationsDetails: (connectionId: string) => `/integrations/${connectionId}`,
  integrationsSchedule: (connectionId: string) => `/integrations/${connectionId}/schedule`,
  administration: "/administration",
  administrationUsers: "/administration/users",
  administrationRoles: "/administration/roles",
  administrationTeams: "/administration/teams",
  administrationInvitations: "/administration/invitations",
  administrationActivityLog: "/administration/activity-log",
  administrationAuditLog: "/administration/audit-log",
  administrationSessions: "/administration/sessions",
  settings: "/settings",
  settingsGeneral: "/settings",
  settingsDevices: "/settings/devices",
  settingsDeviceNew: "/settings/devices/new",
  settingsWorkspaces: "/settings/workspaces",
  settingsPayments: "/settings/payments",
  settingsTaxes: "/settings/taxes",
  settingsZatca: "/settings/zatca",
  settingsCashier: "/settings/cashier",
  madarAdmin: "/madar-admin",
  madarAdminRequests: "/madar-admin/requests",
  madarAdminCustomers: "/madar-admin/customers",
  madarAdminSubscriptions: "/madar-admin/subscriptions",
  madarAdminPackages: "/madar-admin/packages",
  madarAdminCoupons: "/madar-admin/coupons",
  madarAdminSettings: "/madar-admin/settings",
  madarAdminStores: "/madar-admin/stores",
  madarAdminPayments: "/madar-admin/payments",
  madarAdminInvoices: "/madar-admin/invoices",
  madarAdminIntegrations: "/madar-admin/integrations",
  madarAdminTracking: "/madar-admin/tracking",
  madarAdminSystemHealth: "/madar-admin/system-health",
  madarAdminUsers: "/madar-admin/users",
  madarAdminRoles: "/madar-admin/roles",
  madarAdminActivityLog: "/madar-admin/activity-log",
  madarAdminFeatureFlags: "/madar-admin/feature-flags",
  auth: {
    basic: {
      login: "/auth/basic/login",
      register: "/auth/basic/register",
      forgotPassword: "/auth/basic/forgot-password",
      resetPassword: "/auth/basic/reset-password",
      verifyEmail: "/auth/basic/verify-email",
      passwordResetSuccess: "/auth/basic/password-reset-success",
    },
    cover: {
      login: "/auth/cover/login",
      register: "/auth/cover/register",
      forgotPassword: "/auth/cover/forgot-password",
      resetPassword: "/auth/cover/reset-password",
      verifyEmail: "/auth/cover/verify-email",
      passwordResetSuccess: "/auth/cover/password-reset-success",
    },
  },
  login: "/auth/basic/login",
  register: "/auth/basic/register",
  privacy: "/privacy",
  terms: "/terms",
  marketing: {
    product: "/#product",
    integrations: "/#integrations",
    howItWorks: "/#how-it-works",
    about: "/#about",
    contact: "/#contact",
  },
  forgotPassword: "/auth/basic/forgot-password",
  resetPassword: "/auth/basic/reset-password",
  verifyEmail: "/auth/basic/verify-email",
  passwordResetSuccess: "/auth/basic/password-reset-success",
} as const
