import type { AIIntelligenceDashboardDto } from "@/application/contracts"

export const mockAIIntelligenceDashboard: AIIntelligenceDashboardDto = {
  workspaceId: "ws_madar_001",
  generatedAt: "2026-06-21T06:00:00.000Z",
  executiveSummary:
    "Revenue is growing at a healthy pace, but efficiency is slipping in paid search. Meta Ads generated 46% of total revenue while Google Ads CPA increased by 18% week-over-week. Immediate reallocation toward high-LTV cohorts can improve blended ROAS by an estimated 0.3 within 7 days.",
  marketingHealthScore: {
    score: 78,
    delta: 4,
    label: "Stable with optimization opportunities",
  },
  keyInsights: [
    {
      id: "ins_1",
      title: "Meta Ads drives most revenue",
      detail: "Meta Ads generated 46% of total revenue across all paid channels.",
      impact: "High impact on revenue concentration risk.",
      tone: "info",
    },
    {
      id: "ins_2",
      title: "Google Ads CPA is rising",
      detail: "Google Ads CPA increased by 18% compared with last week.",
      impact: "Efficiency is declining in the largest search campaigns.",
      tone: "warning",
    },
    {
      id: "ins_3",
      title: "Snapchat customers show strongest LTV",
      detail: "Customers acquired via Snapchat have the highest projected 90-day LTV.",
      impact: "Upside for scaling this channel with controlled CAC.",
      tone: "success",
    },
  ],
  opportunities: [
    {
      id: "opp_1",
      title: "Scale high-LTV Snapchat lookalikes",
      detail: "Expand top-performing audience set by 20% to capture profitable demand.",
      impact: "Estimated +9% incremental contribution margin.",
      tone: "success",
    },
    {
      id: "opp_2",
      title: "Shift budget from low-converting TikTok ad set",
      detail: "TikTok ROAS decreased for three consecutive days in the largest prospecting ad set.",
      impact: "Can recover 6-8% wasted spend this week.",
      tone: "warning",
    },
  ],
  risks: [
    {
      id: "risk_1",
      title: "Budget concentration in one campaign",
      detail: "41% of paid spend is concentrated in a single campaign.",
      impact: "Single-point performance risk if auction costs spike.",
      tone: "error",
    },
    {
      id: "risk_2",
      title: "High CTR but weak conversion quality",
      detail: "Three campaigns have above-average CTR but below-target conversion rates.",
      impact: "Potential creative-message mismatch post-click.",
      tone: "warning",
    },
  ],
  recommendations: [
    {
      id: "rec_1",
      title: "Rebalance 12% budget toward retention campaigns",
      detail: "Retention campaigns maintain 2.1x better ROAS than cold acquisition this week.",
      impact: "Projected blended ROAS increase from 2.9 to 3.2.",
      tone: "info",
    },
    {
      id: "rec_2",
      title: "Refresh landing page for Search Campaign A",
      detail:
        "Engagement is high but conversion lags after click; page-speed and offer clarity are weak.",
      impact: "Can improve conversion rate by 0.6-1.1 percentage points.",
      tone: "warning",
    },
  ],
  budgetAnalysis: [
    {
      channel: "Meta Ads",
      spend: 58000,
      revenue: 184000,
      roas: 3.17,
      cpa: 27,
      ctr: 2.8,
      conversions: 2140,
      spendShare: 46,
    },
    {
      channel: "Google Ads",
      spend: 42000,
      revenue: 109000,
      roas: 2.6,
      cpa: 38,
      ctr: 3.1,
      conversions: 1102,
      spendShare: 33,
    },
    {
      channel: "TikTok Ads",
      spend: 18000,
      revenue: 36000,
      roas: 2,
      cpa: 41,
      ctr: 2.4,
      conversions: 438,
      spendShare: 14,
    },
    {
      channel: "Snapchat Ads",
      spend: 9000,
      revenue: 29000,
      roas: 3.22,
      cpa: 24,
      ctr: 2.2,
      conversions: 365,
      spendShare: 7,
    },
  ],
  roasAnalysis: [
    { day: "Mon", roas: 2.7, revenue: 42000, spend: 15500 },
    { day: "Tue", roas: 2.8, revenue: 44500, spend: 15900 },
    { day: "Wed", roas: 2.9, revenue: 45800, spend: 15800 },
    { day: "Thu", roas: 3, revenue: 47200, spend: 15700 },
    { day: "Fri", roas: 3.1, revenue: 48500, spend: 15650 },
    { day: "Sat", roas: 2.8, revenue: 43100, spend: 15400 },
    { day: "Sun", roas: 3.2, revenue: 50100, spend: 15600 },
  ],
  channelPerformance: [
    {
      channel: "Meta Ads",
      spend: 58000,
      revenue: 184000,
      roas: 3.17,
      cpa: 27,
      ctr: 2.8,
      conversions: 2140,
      spendShare: 46,
    },
    {
      channel: "Google Ads",
      spend: 42000,
      revenue: 109000,
      roas: 2.6,
      cpa: 38,
      ctr: 3.1,
      conversions: 1102,
      spendShare: 33,
    },
    {
      channel: "TikTok Ads",
      spend: 18000,
      revenue: 36000,
      roas: 2,
      cpa: 41,
      ctr: 2.4,
      conversions: 438,
      spendShare: 14,
    },
    {
      channel: "Snapchat Ads",
      spend: 9000,
      revenue: 29000,
      roas: 3.22,
      cpa: 24,
      ctr: 2.2,
      conversions: 365,
      spendShare: 7,
    },
  ],
  campaignInsights: [
    {
      campaignId: "cmp_041",
      campaignName: "Summer Promo - Meta Retargeting",
      channel: "Meta Ads",
      spend: 18000,
      revenue: 69400,
      roas: 3.86,
      ctr: 3.4,
      conversionRate: 4.9,
    },
    {
      campaignId: "cmp_038",
      campaignName: "Generic Search - GCC",
      channel: "Google Ads",
      spend: 22000,
      revenue: 46800,
      roas: 2.13,
      ctr: 4.2,
      conversionRate: 2.1,
      anomaly: "CTR is strong but conversion dropped 22% after landing-page update.",
    },
    {
      campaignId: "cmp_057",
      campaignName: "TikTok Prospecting - Broad",
      channel: "TikTok Ads",
      spend: 12000,
      revenue: 20300,
      roas: 1.69,
      ctr: 2.7,
      conversionRate: 1.8,
      anomaly: "ROAS declined for three consecutive days.",
    },
  ],
  productInsights: [
    {
      productId: "prd_1001",
      productName: "Smart Hydration Bottle",
      revenue: 68400,
      unitsSold: 1230,
      margin: 41,
      trend: "up",
      insight: "High returning-customer mix is sustaining margin despite rising CPC.",
    },
    {
      productId: "prd_1034",
      productName: "Travel Blender",
      revenue: 39200,
      unitsSold: 910,
      margin: 36,
      trend: "flat",
      insight: "Conversion flattening likely due to increased price comparison traffic.",
    },
    {
      productId: "prd_1088",
      productName: "Fitness Meal Prep Kit",
      revenue: 25100,
      unitsSold: 420,
      margin: 44,
      trend: "down",
      insight: "Traffic quality fell after broad audience expansion.",
    },
  ],
  customerInsights: [
    {
      segment: "High Intent Repeat Buyers",
      acquisitionChannel: "Snapchat Ads",
      ltv: 312,
      cac: 74,
      paybackDays: 29,
      repeatRate: 46,
      insight: "Best LTV/CAC ratio in the portfolio.",
    },
    {
      segment: "Discount-Driven New Users",
      acquisitionChannel: "TikTok Ads",
      ltv: 119,
      cac: 64,
      paybackDays: 53,
      repeatRate: 21,
      insight: "Requires retention automation to improve profitability.",
    },
    {
      segment: "Search Branded Loyalists",
      acquisitionChannel: "Google Ads",
      ltv: 268,
      cac: 81,
      paybackDays: 34,
      repeatRate: 39,
      insight: "Stable profitability but CPC inflation is reducing margin headroom.",
    },
  ],
  anomalyDetection: [
    {
      id: "an_1",
      title: "Unusual CPA spike",
      detail: "Google Ads campaign cmp_038 CPA jumped from SAR 31 to SAR 43 within 48 hours.",
      severity: "high",
      detectedAt: "2026-06-20T22:10:00.000Z",
    },
    {
      id: "an_2",
      title: "ROAS downtrend",
      detail: "TikTok prospecting campaign has shown 3-day consecutive ROAS decline.",
      severity: "medium",
      detectedAt: "2026-06-21T01:20:00.000Z",
    },
  ],
  weeklySummary: {
    wins: [
      "Meta retargeting campaign reached 3.86 ROAS with stable CPA.",
      "Snapchat delivered highest LTV cohort with fastest payback.",
    ],
    watchouts: [
      "Google Ads CPA trend remains elevated.",
      "Budget concentration exceeds recommended 35% threshold in one campaign.",
    ],
    nextActions: [
      "Reduce TikTok broad prospecting budget by 20% and shift to Snapchat high-LTV lookalikes.",
      "Launch landing page experiment for cmp_038 within 48 hours.",
      "Set concentration alert at 35% spend share per campaign.",
    ],
  },
}
