import type {
  CampaignDetailsDto,
  CampaignStatus,
  CreateCampaignRequestDto,
} from "@/application/contracts/campaign.contracts"

function buildCampaign(
  id: string,
  overrides: Partial<CampaignDetailsDto> = {}
): CampaignDetailsDto {
  const base: CampaignDetailsDto = {
    id,
    name: "Campaign",
    status: "active",
    objective: "Increase qualified pipeline from paid channels.",
    channel: "meta",
    owner: "Nora Al-Harbi",
    budget: 120000,
    spend: 84000,
    revenue: 294000,
    roas: 3.5,
    ctr: 2.8,
    cpc: 1.9,
    conversionRate: 4.6,
    startDate: "2026-01-01",
    endDate: "2026-03-31",
    audience: "SMB decision makers",
    country: "Saudi Arabia",
    language: "Arabic",
    overview:
      "Performance campaign focused on acquisition and pipeline growth across paid channels.",
    kpis: {
      totalRevenue: 294000,
      marketingSpend: 84000,
      roas: 3.5,
      cac: 38,
      conversionRate: 4.6,
      websiteVisitors: 61200,
      sessions: 90300,
      bounceRate: 37.6,
      activeCampaigns: 12,
    },
    performance: [
      { month: "Jan", spend: 24000, revenue: 76000, leads: 740 },
      { month: "Feb", spend: 28000, revenue: 96000, leads: 920 },
      { month: "Mar", spend: 32000, revenue: 122000, leads: 1080 },
    ],
    budgetSummary: [
      { label: "Budget", value: 120000 },
      { label: "Spend", value: 84000 },
      { label: "Remaining", value: 36000 },
    ],
    audienceSummary: [
      { segment: "Lookalike 1%", percentage: 35 },
      { segment: "Retargeting", percentage: 28 },
      { segment: "Interest-based", percentage: 22 },
      { segment: "CRM Lists", percentage: 15 },
    ],
    channelsSummary: [
      { channel: "meta", contribution: 42 },
      { channel: "google", contribution: 31 },
      { channel: "tiktok", contribution: 14 },
      { channel: "snapchat", contribution: 8 },
      { channel: "linkedin", contribution: 3 },
      { channel: "email", contribution: 2 },
    ],
    timeline: [
      {
        date: "2026-01-01",
        title: "Campaign launched",
        description: "Initial audience and creative set published.",
      },
      {
        date: "2026-02-08",
        title: "Budget reallocation",
        description: "Shifted 18% spend from low-performing ad sets.",
      },
      {
        date: "2026-03-03",
        title: "Landing page optimization",
        description: "Updated lead form and reduced fields from 7 to 4.",
      },
    ],
    activity: [
      {
        id: `${id}:a1`,
        occurredAt: "2026-03-10T10:20:00.000Z",
        actor: "Nora Al-Harbi",
        action: "Audience updated",
        details: "Added high-intent segment from CRM export.",
      },
      {
        id: `${id}:a2`,
        occurredAt: "2026-03-12T13:45:00.000Z",
        actor: "Omar Al-Qahtani",
        action: "Creative refreshed",
        details: "New video variant deployed for top-performing ad set.",
      },
    ],
    aiRecommendations: [
      "Increase retargeting cap by 12% for the highest converting audience.",
      "Pause two underperforming keyword clusters with CPC above target by 28%.",
      "Test a shorter lead form variant for mobile-first placements.",
    ],
  }

  return {
    ...base,
    ...overrides,
    kpis: {
      ...base.kpis,
      ...(overrides.kpis ?? {}),
    },
    performance: overrides.performance ?? base.performance,
    budgetSummary: overrides.budgetSummary ?? base.budgetSummary,
    audienceSummary: overrides.audienceSummary ?? base.audienceSummary,
    channelsSummary: overrides.channelsSummary ?? base.channelsSummary,
    timeline: overrides.timeline ?? base.timeline,
    activity: overrides.activity ?? base.activity,
    aiRecommendations: overrides.aiRecommendations ?? base.aiRecommendations,
  }
}

export const campaignDetailsMockData: CampaignDetailsDto[] = [
  buildCampaign("cmp_01", {
    name: "Ramadan Growth Sprint",
    status: "active",
    channel: "meta",
    owner: "Nora Al-Harbi",
    budget: 180000,
    spend: 126000,
    revenue: 462000,
    roas: 3.67,
    ctr: 3.2,
    cpc: 1.7,
    conversionRate: 5.1,
    startDate: "2026-02-01",
    endDate: "2026-04-15",
    objective: "Drive online conversions during Ramadan peak demand.",
    audience: "Retail shoppers 18-45",
  }),
  buildCampaign("cmp_02", {
    name: "B2B Pipeline Q2",
    status: "scheduled",
    channel: "linkedin",
    owner: "Rakan Al-Shehri",
    budget: 95000,
    spend: 0,
    revenue: 0,
    roas: 0,
    ctr: 0,
    cpc: 0,
    conversionRate: 0,
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    objective: "Generate enterprise-qualified leads in KSA and UAE.",
    audience: "Directors and VPs in mid-market companies",
  }),
  buildCampaign("cmp_03", {
    name: "Always-on Search",
    status: "active",
    channel: "google",
    owner: "Omar Al-Qahtani",
    budget: 140000,
    spend: 101000,
    revenue: 322000,
    roas: 3.19,
    ctr: 4.1,
    cpc: 2.4,
    conversionRate: 4.4,
    startDate: "2026-01-10",
    endDate: "2026-12-31",
  }),
  buildCampaign("cmp_04", {
    name: "TikTok Product Drop",
    status: "paused",
    channel: "tiktok",
    owner: "Dana Al-Mutairi",
    budget: 78000,
    spend: 64000,
    revenue: 131000,
    roas: 2.05,
    ctr: 2.3,
    cpc: 1.5,
    conversionRate: 2.8,
    startDate: "2026-03-01",
    endDate: "2026-05-31",
  }),
  buildCampaign("cmp_05", {
    name: "Snap Retargeting",
    status: "active",
    channel: "snapchat",
    owner: "Lama Al-Dossary",
    budget: 52000,
    spend: 33900,
    revenue: 98200,
    roas: 2.9,
    ctr: 2.6,
    cpc: 1.3,
    conversionRate: 3.7,
    startDate: "2026-04-01",
    endDate: "2026-06-30",
  }),
  buildCampaign("cmp_06", {
    name: "Email Winback Program",
    status: "completed",
    channel: "email",
    owner: "Maha Al-Salem",
    budget: 28000,
    spend: 24600,
    revenue: 111400,
    roas: 4.53,
    ctr: 5.7,
    cpc: 0.8,
    conversionRate: 6.4,
    startDate: "2026-01-01",
    endDate: "2026-02-28",
  }),
  buildCampaign("cmp_07", {
    name: "Brand Awareness Blast",
    status: "archived",
    channel: "meta",
    owner: "Nora Al-Harbi",
    budget: 65000,
    spend: 65000,
    revenue: 152000,
    roas: 2.34,
    ctr: 1.9,
    cpc: 2.8,
    conversionRate: 2.1,
    startDate: "2025-10-01",
    endDate: "2025-12-31",
  }),
  buildCampaign("cmp_08", {
    name: "Seasonal Shopping Push",
    status: "draft",
    channel: "google",
    owner: "Reem Al-Hazmi",
    budget: 110000,
    spend: 0,
    revenue: 0,
    roas: 0,
    ctr: 0,
    cpc: 0,
    conversionRate: 0,
    startDate: "2026-10-01",
    endDate: "2026-12-15",
  }),
]

export function createCampaignFromPayload(
  id: string,
  payload: CreateCampaignRequestDto,
  nowIso: string
): CampaignDetailsDto {
  const status: CampaignStatus = payload.status

  return buildCampaign(id, {
    ...payload,
    id,
    status,
    spend: 0,
    revenue: 0,
    roas: 0,
    ctr: 0,
    cpc: 0,
    conversionRate: 0,
    overview: `${payload.name} campaign created and pending optimization cycles.`,
    timeline: [
      {
        date: payload.startDate,
        title: "Campaign scheduled",
        description: "Campaign was created and scheduled for launch.",
      },
    ],
    activity: [
      {
        id: `${id}:created`,
        occurredAt: nowIso,
        actor: payload.owner,
        action: "Campaign created",
        details: "Initial configuration saved from campaign form.",
      },
    ],
  })
}
