import type { Role } from "../../types"

// Fixed, non-editable default permission matrices for the platform's real
// membership roles -- unlike custom roles, these are not backed by
// custom_role_permissions and don't affect actual authorization checks (those
// still run on the fixed owner/admin/manager/analyst/viewer role system).
// This just gives the granular Roles UI (and team role assignment) something
// honest to display and reference for the roles a member can actually be
// assigned.
export const SYSTEM_ROLE_DEFINITIONS: Array<{
  role: Role
  name: string
  description: string
  permissions: Record<string, string[]>
}> = [
  {
    role: "owner",
    name: "Owner",
    description: "Full control across security, operations, and workspace governance.",
    permissions: {
      dashboard: ["view", "export"],
      liveVisitors: ["view"],
      campaigns: ["view", "create", "edit", "delete", "approve", "publish", "manage"],
      customers: ["view", "create", "edit", "delete", "export", "import"],
      products: ["view", "create", "edit", "delete", "export", "import"],
      orders: ["view", "export"],
      pos: ["view", "manage"],
      suppliers: ["view", "manage"],
      purchases: ["view", "manage"],
      expenses: ["view", "manage"],
      reports: ["view", "export", "approve", "manage"],
      connections: ["view", "create", "edit", "delete", "manage"],
      stores: ["view"],
      ai: ["view", "manage"],
      tax: ["view", "manage"],
      settings: ["view", "edit", "manage"],
      workspace: ["view", "edit", "manage"],
      users: ["view", "create", "edit", "delete", "manage"],
      roles: ["view"],
      teams: ["view"],
      invitations: ["view"],
      auditLog: ["view"],
      sessions: ["view"],
    },
  },
  {
    role: "admin",
    name: "Admin",
    description: "Manages users, roles, and operational settings.",
    permissions: {
      dashboard: ["view"],
      liveVisitors: ["view"],
      campaigns: ["view", "create", "edit", "delete", "approve", "publish", "manage"],
      customers: ["view"],
      products: ["view"],
      orders: ["view"],
      pos: ["view", "manage"],
      suppliers: ["view", "manage"],
      purchases: ["view", "manage"],
      expenses: ["view", "manage"],
      reports: ["view", "manage"],
      connections: ["view"],
      stores: ["view"],
      ai: ["view"],
      tax: ["view", "manage"],
      settings: ["view", "edit", "manage"],
      workspace: ["view", "edit", "manage"],
      users: ["view", "create", "edit", "delete", "manage"],
      roles: ["view"],
      teams: ["view"],
      invitations: ["view"],
      auditLog: ["view"],
      sessions: ["view"],
    },
  },
  {
    role: "manager",
    name: "Manager",
    description: "Owns campaign planning, approvals, and reporting.",
    permissions: {
      dashboard: ["view"],
      liveVisitors: ["view"],
      campaigns: ["view", "create", "edit", "approve", "publish"],
      customers: ["view"],
      products: ["view"],
      orders: ["view"],
      pos: ["view"],
      suppliers: ["view"],
      purchases: ["view"],
      expenses: ["view"],
      reports: ["view", "export", "manage"],
      connections: ["view"],
      stores: ["view"],
      ai: ["view"],
      tax: ["view"],
      settings: ["view"],
      workspace: ["view"],
      users: ["view"],
      roles: ["view"],
      teams: ["view"],
      invitations: ["view"],
      auditLog: ["view"],
    },
  },
  {
    role: "analyst",
    name: "Analyst",
    description: "Analyzes KPI trends and exports reporting data.",
    permissions: {
      dashboard: ["view", "export"],
      liveVisitors: ["view"],
      campaigns: ["view"],
      customers: ["view"],
      products: ["view"],
      orders: ["view"],
      pos: ["view"],
      suppliers: ["view"],
      purchases: ["view"],
      expenses: ["view"],
      reports: ["view", "export"],
      connections: ["view"],
      stores: ["view"],
      ai: ["view"],
      tax: ["view"],
      settings: ["view"],
      workspace: ["view"],
      users: ["view"],
      roles: ["view"],
      teams: ["view"],
      invitations: ["view"],
      auditLog: ["view"],
    },
  },
  {
    role: "viewer",
    name: "Viewer",
    description: "Read-only access across approved modules.",
    permissions: {
      dashboard: ["view"],
      liveVisitors: ["view"],
      campaigns: ["view"],
      customers: ["view"],
      products: ["view"],
      orders: ["view"],
      pos: ["view"],
      suppliers: ["view"],
      purchases: ["view"],
      expenses: ["view"],
      reports: ["view"],
      connections: ["view"],
      stores: ["view"],
      ai: ["view"],
      tax: ["view"],
      settings: ["view"],
      workspace: ["view"],
      users: ["view"],
      roles: ["view"],
      teams: ["view"],
      invitations: ["view"],
      auditLog: ["view"],
    },
  },
]
